# Generated by Django 3.1.2 on 2023-10-01 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230928_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='upload',
            name='contactnum',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
