# Generated by Django 3.1.2 on 2023-10-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20231001_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
