# Generated by Django 3.1.2 on 2023-10-01 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=260)),
                ('contactnum', models.CharField(max_length=15, null=True)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
